---
drain_grace_period: 30
drain_timeout: 36s
drain_pod_selector: ""
drain_nodes: true
drain_retries: 1
drain_retry_delay_seconds: 10

drain_fallback_enabled: false
drain_fallback_grace_period: 30
drain_fallback_timeout: 36s
drain_fallback_retries: 0
drain_fallback_retry_delay_seconds: 10

upgrade_node_always_cordon: false
upgrade_node_uncordon_after_drain_failure: true
upgrade_node_fail_if_drain_fails: false

upgrade_node_confirm: false
upgrade_node_pause_seconds: 0
